### ISSUE TITLE
On landscape mode side menu does not scroll and have area error (yellow and black)

### ISSUE THREAD

**Issue by alexi190** [medyas/flutter_zoom_drawer#14]
Hi I tried to wrap it in Expanded widget but then menu does not shows. How can make menus scrollable in landscape mode

**Comment by medyas** [comment]
@peswanibros This plugin allows to implement the drawer and it's up to you to support both portrait and landscape layout in you build method.
If you run the example app, and had overflow errors, it's because i have not tested it on landscape, your more then welcome to submit a pull request with a fix of the error otherwise each person will implement the plugin in his/her own project and have support for the orientation they need.

**Comment by YouSour** [comment]
@medyas hi , i try to wrap it with singleChildScrollView but it isn't work, how to fix it ?
