### ISSUE TITLE
can't close drawer

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [medyas/flutter_zoom_drawer#16]
Hi, a dear friend  can you help me  when I open a drawer from the menu icon on the home screen I can't close it from the home screen when press on the same button opens the drawer 
after downloading the example and run it the is the same only close when drag to left.
 how can I fix it? 
 I need to close the drawer from the same menu button I open it from?
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-14 at 10 01 44](https://user-images.githubusercontent.com/6634311/93059817-8f0db900-f671-11ea-9492-fe85fde145e7.png)

**Comment by Eng-MohamedGadala** [comment]
@medyas

**Comment by medyas** [comment]
Hello, The app already have a toggle function set on the Drawer button [Link](https://github.com/medyas/flutter_zoom_drawer/blob/a431ba536ab69af0e05cdefdbfa64084a1449b74/example/lib/page_structure.dart#L61). But with the updates to the example as a lot of people ask how to implement stuff in the example app, i had to change some things and that's why the example app Drawer toggle does not work.
To get this to work you will have to update the MainScreen build method:
This snippet will only allow toggling of the Drawer by the Menu Icon.

```Dart

class _MainScreenState extends State<MainScreen> {
  @override
  Widget build(BuildContext context) {
    return PageStructure();
  }
}
```

**Comment by Eng-MohamedGadala** [comment]
ok thanks It's work
