### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by mustafa-fahimi** [medyas/flutter_zoom_drawer#41]
Hi. When I set RTL to true then at the start of the screen the drawer is open for one second and then it close. This happens only in RTL mode.
My app Locale is "fa" and my device language is English.
It happens in your last update.

**Comment by medyas** [comment]
@Tokenizer94 sorry for the late answer, will try to check this in the weekend

**Comment by medyas** [comment]
just tested with device locale en and app locale ar, and this issue did not occur.
Can you provide reproducible example

**Comment by mustafa-fahimi** [comment]
@medyas This happens when the version is above 2.0.2. 
Maybe it's because you added the Persian language ("fa") into the RTL list. But I'm not sure about it.

**Comment by medyas** [comment]
well i tested with the latest version.
can you provide a sample project ?

**Comment by EngAL-shikh** [comment]
LTR not working 
so border

**Comment by medyas** [comment]
@EngAL-shikh  can you provide more details ?

**Comment by EinatK** [comment]
This is what happens when not to set RTL . Used to work perfectly. 
My device and app locale is English US

Any suggestions on a quick fix ? It's pretty urgent for me  
![zoom_drawer_ltr](https://user-images.githubusercontent.com/16320455/129540923-afe064c1-afb2-4bd2-be3d-f211be24353d.jpg)

Just for reference - this is how it should look. The only thing that changed was setting isRtl: true on the drawer. Everything gets zoomed and pushed to the left.. 

![zoom_drawer_ltr_correct](https://user-images.githubusercontent.com/16320455/129542522-c7f495a3-ddd5-456a-8d65-f4ddad33faa3.jpg)

**Comment by medyas** [comment]
@EinatK why are you setting `rtl` to true when your not support RTL direction in you app ?

**Comment by EinatK** [comment]
@medyas This was initially an RTL demo app and then we wanted an English demo version so i removed the rtl support and set the drawer rtl to false and this was the result

**Comment by medyas** [comment]
can you provide a working demo to reproduce this issue ?

**Comment by EinatK** [comment]
Here you go, simple counter app with latest zoom drawer

https://github.com/EinatK/zoom_drawer_ltr_bug

**Comment by medyas** [comment]
ok will check it when i have time

**Comment by medyas** [comment]
@EinatK just published a new version with a fix

**Comment by EinatK** [comment]
Wow you're fast! 
Thanks dude working great ! Awesome package :)
